from . import res_config
from . import product_category
from . import product_glass
from . import product_glass_edge
from . import product_glass_shape
from . import product_glass_finish
from . import product_glass_braces
from . import product_glass_extras
from . import product_glass_dimconstraint
from . import res_partner
from . import sale_order
from . import sale_order_line
from . import sale_order_line_sub
from . import product_template
